kind: pipeline
type: docker
name: default

steps:
- name: deploy
  image: danielzendejas/albumcharts:1.0.0
  environment:
    REACT_APP_HOST: http://albumcharts.xyz
  commands:
  - npm run-script build
  - aws s3 sync build/ s3://albumcharts.xyz
